Adiciona ci pipeline
mentoriaiac/template-packer pull request #4
Opened 2021-05-16 09:50 UTC by lariskovski

Adiciona pipeline com packer validate

2021-05-16 15:51 UTC, gomex requested changes
Ta muito bom. Tem apenas alguns detalhes pra olhar.

2021-05-16 15:51 UTC, gomex commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Devemos sempre usar uma versão especifica quando possível.

https://docs.github.com/pt/actions/reference/workflow-syntax-for-github-actions

Nesse caso o valor deve ser "ubuntu-20.04"

2021-05-16 15:51 UTC, gomex commented on .github/workflows/ci.yml
> +        uses: hashicorp/packer-github-actions@master
Esse action tem uma tag. Vamos usar a tag ao invés da branch master podemos usar a tag: "v0.2.0"

https://github.com/hashicorp/packer-github-actions/releases

2021-05-16 15:51 UTC, gomex commented on .github/workflows/ci.yml
> +name: Packer
Isso é o nome do seu workflow. Acho que colocar uma coisa que seja mais clara com relação a seu objetivo com esse workflow aqui.

O que ele ta fazendo? Basicamente CI, né? eu trocaria pra CI o nome, mas podemos pensar em outro também.

2021-05-16 22:00 UTC, gomex requested changes
Está ótimo, mas precisa de pequenas modificações.

2021-05-16 22:00 UTC, gomex commented on .github/workflows/ci.yml
> +    name: packer
O que acha de mudar o nome para "Validação"

2021-05-22 16:15 UTC, lariskovski commented on .github/workflows/ci.yml
> +    name: packer
No [commit](https://github.com/mentoriaiac/template-packer/pull/4/commits/f2a200c048a807aab2a702585b7572cebef1cded) alterei o nome para "Validation" para seguir o padrão de nomes em inglês. Se achar melhor podemos mudar pra português.

2021-05-22 16:26 UTC, gomex approved these changes

2021-05-22 16:26 UTC, merged